version: "3.6"

services:
  fastapi:
    build:
        context: src
        dockerfile: ./docker/Dockerfile
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - HASH_TOKEN=${HASH_TOKEN}
      - CIPHER_TYPE=${CIPHER_TYPE}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./src:/home/python/app

  db:
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    volumes:
    - postgresql_db_new:/var/lib/postgresql/data
    - ./postgres-db/:/restore/:ro
    ports:
      - "5444:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}


  pg-admin:
    image: dpage/pgadmin4:8.11.0
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "4080:80"
    volumes:
      - pg_admin_volume:/var/lib/pgadmin


volumes:
  postgresql_db_new:
  pg_admin_volume: